GLOBALREF INT tst_detecteur (INT, STRING, INT, INT *);
GLOBALREF INT tst_acquisition (STRING, INT);
GLOBALREF INT tst_divers (STRING, INT);
GLOBALREF INT tst_aff (STRING, INT);
GLOBALREF INT tst_alarme (STRING, INT);
GLOBALREF INT format_date (STRING, LONG);
